<?xml version="1.0" ?>
<robot name="solo"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  <xacro:property name="base_w" value=".2" />
  <xacro:property name="base_l" value=".4" />
  <xacro:property name="base_h" value=".05" />
  <xacro:property name="base_m" value="2.0" />

  <xacro:property name="upper_leg_length" value="0.16" />
  <xacro:property name="upper_leg_radius" value="0.025" />
  <xacro:property name="upper_leg_mass" value="0.162" />
  <xacro:property name="lower_leg_mass" value="0.021" />

  <xacro:macro name="leg" params="prefix rx ry">
    <joint name="${prefix}_HFE" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_upperleg"/>
      <limit effort="1000" lower="-10" upper="10" velocity="1000"/>
      <axis xyz="0 1 0"/>
      <origin rpy="0 0 0" xyz="${rx} ${ry} 0"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}_upperleg">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-.5*upper_leg_length}"/>
        <geometry>
          <!-- <cylinder length="${upper_leg_length}" radius="${upper_leg_radius}"/> -->
          <mesh filename="package://robot_properties_solo/meshes/cylinder.obj" scale="${upper_leg_radius} ${upper_leg_radius} ${upper_leg_length}"/>
        </geometry>
        <material name="grey">
          <color rgba=".4 .4 .4 .1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-.5*upper_leg_length}"/>
        <geometry>
          <cylinder length="${upper_leg_length}" radius="${upper_leg_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 -0.0793"/>
        <mass value="${upper_leg_mass}"/>
        <inertia ixy="0.0" ixz="0.0" iyz="0.0"
          ixx="0.000469609"
          iyy="0.000469609"
          izz="1e-6"/>
      </inertial>
    </link>

    <joint name="${prefix}_KFE" type="revolute">
      <parent link="${prefix}_upperleg"/>
      <child link="${prefix}_shank"/>
      <limit effort="1000" velocity="10000"/>
      <axis xyz="0 1 0"/>
      <origin rpy="0 0 0" xyz="0 0 ${-upper_leg_length}"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>


    <link name="${prefix}_shank">
      <contact>
          <lateral_friction value="1.0"/>
          <restitution value="0.5"/>
      </contact>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-.5*upper_leg_length}"/>
        <geometry>
          <!-- <cylinder length="${upper_leg_length}" radius="${upper_leg_radius}"/> -->
          <mesh filename="package://robot_properties_solo/meshes/cylinder.obj" scale="${upper_leg_radius} ${upper_leg_radius} ${upper_leg_length}"/>
        </geometry>
        <material name="grey">
          <color rgba=".4 .4 .4 .1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-.5*upper_leg_length}"/>
        <geometry>
          <cylinder length="${upper_leg_length}" radius="${upper_leg_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 -0.0756"/>
        <mass value="${lower_leg_mass}"/>
        <inertia ixy="0.0" ixz="0.0" iyz="0.0"
          ixx="0.000087575"
          iyy="0.000087575"
          izz="1e-6"/>
    </inertial>
    </link>

    <joint name="${prefix}_END" type="fixed">
      <parent link="${prefix}_shank"/>
      <child link="${prefix}_contact"/>
      <origin rpy="0 0 0" xyz="0 0 ${-upper_leg_length}"/>
    </joint>

    <link name="${prefix}_contact">
      <contact>
          <lateral_friction value="1.0"/>
          <restitution value="0.5"/>
      </contact>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <!-- <sphere radius="${upper_leg_radius}"/> -->
          <mesh filename="package://robot_properties_solo/meshes/sphere.obj" scale="${upper_leg_radius} ${upper_leg_radius} ${upper_leg_radius}"/>
        </geometry>
        <material name="red">
          <color rgba="1. 0. 0. 1."/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="${upper_leg_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixy="0.0" ixz="0.0" iyz="0.0"
          ixx="0."
          iyy="0."
          izz="0."/>
    </inertial>
    </link>
  </xacro:macro>

  <link name="base_link">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${base_m}"/>
        <inertia ixx="${1./12. * base_m * (base_h*base_h + base_w*base_w)}"
                 iyy="${1./12. * base_m * (base_h*base_h + base_l*base_l)}"
                 izz="${1./12. * base_m * (base_w*base_w + base_l*base_l)}"
                 ixy="0" ixz="0" iyz="0"
        />
    </inertial>
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_properties_solo/meshes/cube.obj" scale="${base_l} ${base_w} ${base_h}"/>
        </geometry>
        <material name="white">
            <color rgba="1 1 1 1"/>
        </material>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="${base_l} ${base_w} ${base_h}"/>
        </geometry>
    </collision>
  </link>

  <!-- <xacro:leg prefix="FL" rx="${0.}" ry="${0.}"/> -->

  <xacro:leg prefix="FL" ry="${+0.5*base_w}" rx="${0.5*base_l}"/>
  <xacro:leg prefix="FR" ry="${-0.5*base_w}" rx="${0.5*base_l}"/>
  <xacro:leg prefix="HL" ry="${+0.5*base_w}" rx="${-0.5*base_l}"/>
  <xacro:leg prefix="HR" ry="${-0.5*base_w}" rx="${-0.5*base_l}"/>
</robot>
